# Configure main menu and social menu

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/sjtseng0924"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/%E5%A3%AB%E7%8F%8D-%E6%9B%BE-125166331/"

[social.params]
icon = "brand-linkedin"
